<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>GameWatchConUpdater</AssemblyName>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>Build\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>Build\Release\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedCore\SharedCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Build\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Build\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Build\**" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Octokit" Version="14.0.0" />
      <PackageReference Include="Semver" Version="3.0.0" />
      <PackageReference Include="SharpCompress" Version="0.49.1" />
    </ItemGroup>

</Project>
