<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <!-- For IDE intellisense -->
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>../out/dev/dbg/Libraries/Core</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>../out/dev/rel/Libraries/Core</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.79"/>
        <PackageReference Include="Dapper.AOT" Version="1.0.52"/>
        <PackageReference Include="Google.Protobuf" Version="3.35.1"/>
        <PackageReference Include="Grpc.Tools" Version="2.83.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="GrpcDotNetNamedPipes" Version="3.1.0"/>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="11.0.0-preview.6.26359.118"/>
    </ItemGroup>

    <PropertyGroup>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Dapper.AOT</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="Protos\game_monitor.proto" GrpcServices="Both"/>
    </ItemGroup>

</Project>