<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <UserSecretsId>dotnet-GameWatch.Agent.GameMonitor-bd37f76d-b04a-478c-aa77-51e3c4668559</UserSecretsId>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>C:\Users\alex\Documents\Dev\Projects\GameWatch\build\debug\GameWatch\Agents\GameMonitor\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>C:\Users\alex\Documents\Dev\Projects\GameWatch\build\release\GameWatch\Agents\GameMonitor\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GrpcDotNetNamedPipes" Version="3.1.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameWatch.Core\GameWatch.Core.csproj" />
    </ItemGroup>
</Project>
