<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <UserSecretsId>dotnet-GameWatch.Agent.GameMonitor-bd37f76d-b04a-478c-aa77-51e3c4668559</UserSecretsId>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameWatch.Core\GameWatch.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- 1. Bundle appsettings files into the Single-File executable -->
        <Content Update="appsettings*.json" ExcludeFromSingleFile="false" />

        <!-- 2. Prevent MSBuild from copying loose appsettings files into the output directory on Publish -->
        <Content Update="appsettings*.json" CopyToPublishDirectory="Never" />
    </ItemGroup>

</Project>
