<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <Company>AlexDeFoc</Company>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <FileVersion>2.0.0.0</FileVersion>
        <InformationalVersion>2.0.0</InformationalVersion>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <PublicSign>false</PublicSign>
        <Copyright>Copyright (c) AlexDeFoc $([System.DateTime]::Now.Year)</Copyright>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.CommandLine" Version="3.0.0-preview.5.26302.115" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameWatch.FileManager\GameWatch.FileManager.csproj" />
    </ItemGroup>

</Project>